### ISSUE TITLE
LOGGGING: Logging of Game playing actions, for each player 

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#1]
Logging of Game Playing actions, for each player .

We don't need to have summaries of actions, just a "play event log" table that saves the visited states.

Logging document is here:

https://docs.google.com/document/d/1amIR30Kc2pnC49rOeGNDylbaePApeflzGBJHEZzHzuU/edit

Login
Each Visited state and by which user
Time in visited state
Transitions: Inputs/Answers given 
From the states table info we should be able to retrieve: Correct/incorrect states, hint states

**Comment by mmicciolo** [comment]
Hello @franciscastro and @IvonArroyo 

Logging of the game player can now move forward. In issue #171 I made some changes to the game instance table.

The table now supports storing player history with the addition of the following new fields:

```java
	@ElementCollection
	private List<GameInstancePlayer> players = new ArrayList<GameInstancePlayer>();
```

A GameInstancePlayer stores the usernameId and whether its a temporary one or not.

Francis can now use this table to link his log events in wlcp-metrics to a game instance. And it can also be used to link player related information such as individual player statistics.

**Comment by franciscastro** [comment]
We are prioritizing doing this on the Android app first, as there is significant development on the app for logging and because we are steering towards using the app as our primary player interface (with mobile web browser as secondary player interface)

CC: @apoh3

**Comment by mmicciolo** [comment]
Using this comment to track progress on this issue.

Will be broken down into 2 phases : 

# Phase 1
Updating the UI's button logging now that new features have been added.

## Login
- [x] ✅ Login - Login Button (Success / Error)
- [x] ✅ Login - Register Button (Success / Error)

## Mode Selection
- [x] ✅ Mode Selection - Tiles (Game Manager, Game Editor, Game Player)
- [x] ✅ Mode Selection - ? Button
- [x] ✅ Mode Selection - Logout Button (Success / Error)

## Game Editor
- [x] ✅ Game Editor - Save History Button
- [x] ✅ Game Editor - Save History Button - Save History Item Selected
- [x] ✅ Game Editor - Save History Button - Revert To Button
- [x] ✅ Game Editor - Save History Button - Revert To Button - OK
- [x] ✅ Game Editor - Save History Button - Revert To Button - Cancel
- [x] ✅ Game Editor - Save History Button - View Button
- [ ] Game Editor - Save History Button - View Button - Disable Logging In Read Only
- [x] ✅ Game Editor - Save History Button - View Button - Back To Editor
- [x] ✅ Game Editor - Label and Save Button
- [x] ✅ Game Editor - Label and Save - Label And Save
- [x] ✅ Game Editor - Label and Save - Cancel
- [x] ✅ Game Editor - Undo Button
- [x] ✅ Game Editor - Redo Button
- [x] ✅ Game Editor - Run and Debug - Start New Debug
- [x] ✅ Game Editor - Run and Debug - Debug As New Player
- [x] ✅ Game Editor - Run and Debug - Cancel
- [x] ✅ Game Editor - Run and Debug - Back Button
- [x] ✅ Game Editor - Run and Debug - Close Current Debugger
- [x] ✅ Game Editor - Run and Debug - Close All Debuggers
- [x] ✅ Game Editor - Load Button - Load
- [x] ✅ Game Editor - Load Button - Cancel
- [x] ✅ Game Editor - Start State - Double Click
- [x] ✅ Game Editor - Start State - Accept
- [x] ✅ Game Editor - Start State - Cancel

# Phase 2
This phase will be adding logging to the game player via server side. This will allow us to do things like track time within states and make it so game clients won't have to implement as much logging code.

## Client Message Logging
- [x] ✅ Game Player - Known User
- [x] ✅ Game Player - Guest User
- [x] ✅ Game Player - Game Full
- [x] ✅ Game Player - Enter Name
- [x] ✅ Game Player - Name Taken
- [x] ✅ Game Player - Name Taken User Reconnects as Existing User
- [x] ✅ Game Player - Name Taken User Selects New Name
- [x] ✅ Game Player - Choose Team And Player
- [x] ✅ Game Player - Choose Team And Player - Game Instance Full
- [x] ✅ Game Player - Connected
- [x] ✅ Game Player - Exit

## Server Message Logging
- [x] ✅ Game Instance Started
- [x] ✅ Game Instance Stopped
- [x] ✅ Connect
- [x] ✅ Reconnect
- [x] ✅ Disconnect

## Server Event Logging
- [x] ✅ Enter State
- [x] ✅ Exit State
- [x] ✅ Enter Transition
- [x] ✅ Exit Transition

## Communication Logging
- [x] ✅ Client Receive Output Request (None, Display Text, Display Photo, Play Sound, Play Video)
- [x] ✅ Client Receive Input Request (None, Single Button Press, Sequence Button Press, Keyboard Input, Timer, Random)
- [x] ✅ Client Send Input (Single Button Press, Sequence Button Press, Keyboard Input, Timer, Random)
- [x] ✅ Server Receive Input (Single Button Press, Sequence Button Press, Keyboard Input, Timer, Random)
- [x] ✅ Server Send Output Request (None, Display Text, Display Photo, Play Sound, Play Video)
- [x] ✅ Server Send Input Request (None, Single Button Press, Sequence Button Press, Keyboard Input, Timer, Random)
